---
- name: Download Java and Install
  yum: name=java-1.8.0-openjdk-devel.x86_64 state=present

- name: Install wget
  yum: name=wget state=present

- name: Install SetupTools
  shell: wget https://bootstrap.pypa.io/ez_setup.py -O - | python

- name: Install Supervisor
  shell: easy_install supervisor

- name: Install Python libselinux to run Supervisor
  yum: name=libselinux-python.x86_64 state=present

- name: Install Supervisor init script
  copy: src=supervisor dest=/etc/init.d/supervisor owner=root group=root mode=0755

- name: Configure supervisor to start at boot
  service: name=supervisor enabled=yes

- name: Create Supervisor log file directory
  file: path=/var/log/supervisor mode=0700 state=directory

- name: Create Supervisor log file
  copy: content="" dest=/var/log/supervisor/supervisord.log mode=0600

- name: Install Htop
  yum: name=htop state=present

- name: Install Nmap
  yum: name=nmap state=present

- name: Install Nano
  yum: name=nano state=present

- name: Install Unzip
  yum: name=unzip state=present

- name: Install Lynx
  yum: name=lynx state=present

- name: Install GCC to compile Authbind
  yum: name=gcc.x86_64 state=present

- name: Download Authbind
  get_url:
    url=http://ftp.debian.org/debian/pool/main/a/authbind/authbind_2.1.1.tar.gz
    dest=/tmp/authbind.tar.gz
    sha256sum=65b26b83b7ca5aa713524e0aff439f71a0ba8970913768457a22239540a9c73a

- name: Unpack Authbind
  unarchive: src=/tmp/authbind.tar.gz dest=/tmp copy=no

- name: Change Authbind's Makefile prefix
  shell: sed -i -e 's|prefix=/usr/local|prefix=/usr|' "/tmp/authbind-2.1.1/Makefile"

- name: Compile and install Authbind
  shell: make install
  args:
    chdir: /tmp/authbind-2.1.1

- name: Configure Authbind's secure HTTP port
  copy: content="" dest=/etc/authbind/byport/443 owner=sinai mode=0500

- name: Configure Authbind's non-secure HTTP port
  copy: content="" dest=/etc/authbind/byport/80 owner=sinai mode=0500